services:
  - type: web
    name: voting-system
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: voting-db
          property: connectionString

databases:
  - name: voting-db
    plan: free
    databaseName: voting_db
    user: voting_user